[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["color", "derive"] }
rand = "0.9.1"

[[bin]]
name = "raytracer"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
