name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --verbose --future-incompat-report
      - name: test
        run: cargo test --verbose --no-fail-fast --future-incompat-report
